import Vue from "vue";
import App from "./App.vue";

// Import autogenerated fontawesome imports
import "@/plugins/fontawesome-autogen.js";

// Import regular fontawesome component
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
Vue.component("fa", FontAwesomeIcon);

Vue.config.productionTip = false;

new Vue({
  render: h => h(App)
}).$mount("#app");
