import Vue from "vue";
import App from "./App.vue";

import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
Vue.component("font-awesome-icon", FontAwesomeIcon);

import "@/plugins/fontawesome-autogen.js"; // Import autogenerated fontawesome imports

Vue.config.productionTip = false;

new Vue({
  render: (h) => h(App),
}).$mount("#app");
